import type {
  VaultItem,
  Passkey,
  OtpAccount,
  VaultDocument,
  ShareInvite,
  Device,
  Session,
  ActivityEvent,
  Invoice,
} from "./vault-types";

const now = Date.now();
const days = (n: number) => now - n * 86_400_000;

export const seedItems: VaultItem[] = [
  {
    id: "itm_1",
    type: "password",
    title: "GitHub",
    domain: "github.com",
    username: "pavank@novasafe.io",
    password: "G7!h$Pa9wzQx-2026",
    url: "https://github.com",
    notes: "Primary dev account. 2FA via TOTP.",
    tags: ["work", "dev"],
    favorite: true,
    vault: "Personal",
    createdAt: days(312),
    updatedAt: days(4),
    lastOpenedAt: days(1),
    history: [
      {
        id: "ph_1",
        password: "G6!h$Pa9wzQx-2025",
        createdAt: days(180),
        active: false,
      },
      {
        id: "ph_2",
        password: "OldGit#2024-pass",
        createdAt: days(400),
        active: false,
      },
    ],
    otpSecret: "JBSWY3DPEHPK3PXP",
    breached: false,
    customFields: [
      {
        id: "cf_1",
        name: "Recovery email",
        value: "pavank.recovery@gmail.com",
        isSensitive: false,
        type: "EMAIL",
      },
    ],
  },
  {
    id: "itm_2",
    type: "password",
    title: "Figma",
    domain: "figma.com",
    username: "pavank@novasafe.io",
    password: "Fg#2026-design-LK",
    url: "https://figma.com",
    tags: ["design", "work"],
    favorite: false,
    vault: "Personal",
    createdAt: days(220),
    updatedAt: days(20),
    lastOpenedAt: days(2),
    history: [],
    breached: false,
  },
  {
    id: "itm_3",
    type: "password",
    title: "Netflix",
    domain: "netflix.com",
    username: "pavan.family@gmail.com",
    password: "letme1n",
    tags: ["family"],
    favorite: false,
    vault: "Family",
    createdAt: days(700),
    updatedAt: days(120),
    lastOpenedAt: days(10),
    history: [],
    breached: true,
  },
  {
    id: "itm_4",
    type: "card",
    title: "HDFC Platinum",
    cardNumber: "4539 1488 0343 6467",
    cardHolder: "Pavankumar Tidke",
    cardExpiry: "11/29",
    cardCvv: "318",
    tags: ["bank"],
    favorite: true,
    vault: "Personal",
    createdAt: days(500),
    updatedAt: days(30),
    lastOpenedAt: days(3),
    history: [],
  },
  {
    id: "itm_5",
    type: "identity",
    title: "Passport — IN",
    identity: {
      fullName: "Pavankumar Tidke",
      number: "M8392041",
      country: "India",
      expiry: "2031-06-12",
    },
    tags: ["id"],
    favorite: false,
    vault: "Personal",
    createdAt: days(900),
    updatedAt: days(200),
    lastOpenedAt: days(60),
    history: [],
  },
  {
    id: "itm_6",
    type: "ssh",
    title: "prod-bastion",
    username: "ubuntu",
    sshKey:
      "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAA…\n-----END OPENSSH PRIVATE KEY-----",
    notes: "ed25519, fingerprint SHA256:7Ld…",
    tags: ["infra", "work"],
    favorite: false,
    vault: "Work",
    createdAt: days(150),
    updatedAt: days(8),
    lastOpenedAt: days(5),
    history: [],
  },
  {
    id: "itm_7",
    type: "apikey",
    title: "OpenAI — production",
    username: "novasafe-prod",
    password: "sk-proj-•••••••••••••••••a93f",
    tags: ["api", "work"],
    favorite: false,
    vault: "Work",
    createdAt: days(60),
    updatedAt: days(2),
    lastOpenedAt: days(0),
    history: [],
  },
  {
    id: "itm_8",
    type: "wifi",
    title: "Home — Nova_5G",
    username: "Nova_5G",
    password: "MoonRiver$1842",
    tags: ["home"],
    favorite: false,
    vault: "Personal",
    createdAt: days(420),
    updatedAt: days(420),
    lastOpenedAt: days(40),
    history: [],
  },
  {
    id: "itm_9",
    type: "crypto",
    title: "Ledger Nano Seed",
    notes: "24-word recovery — stored encrypted.",
    password:
      "shadow forest pillow gentle ridge tornado clover satellite breeze marble copper banana orchid tunnel quartz embrace velvet lantern mango thunder petal jungle anchor wisdom",
    tags: ["crypto"],
    favorite: true,
    vault: "Personal",
    createdAt: days(180),
    updatedAt: days(180),
    lastOpenedAt: days(90),
    history: [],
  },
  {
    id: "itm_10",
    type: "note",
    title: "Apartment lease — clauses",
    notes: "Notice period 60 days. Rent due 5th. Maintenance ₹3,200/mo.",
    tags: ["personal"],
    favorite: false,
    vault: "Personal",
    createdAt: days(30),
    updatedAt: days(7),
    lastOpenedAt: days(7),
    history: [],
  },
  {
    id: "itm_11",
    type: "server",
    title: "Hetzner — eu-fsn-01",
    username: "root",
    password: "Hx-9Sb*7zRkqP",
    url: "ssh://eu-fsn-01.novasafe.internal",
    tags: ["infra", "work"],
    favorite: false,
    vault: "Work",
    createdAt: days(95),
    updatedAt: days(14),
    lastOpenedAt: days(2),
    history: [],
  },
  {
    id: "itm_12",
    type: "license",
    title: "Sketch — lifetime",
    username: "pavank@novasafe.io",
    password: "SKCH-LT-2026-9QX2-MN82-7PB0",
    tags: ["software"],
    favorite: false,
    vault: "Personal",
    createdAt: days(380),
    updatedAt: days(380),
    lastOpenedAt: days(120),
    history: [],
  },
];

export const seedPasskeys: Passkey[] = [
  {
    id: "pk_1",
    service: "Google",
    domain: "google.com",
    device: "MacBook Pro 16″",
    platform: "macOS",
    createdAt: days(60),
    lastUsedAt: days(1),
    synced: true,
    biometric: true,
  },
  {
    id: "pk_2",
    service: "GitHub",
    domain: "github.com",
    device: "iPhone 17 Pro",
    platform: "iOS",
    createdAt: days(45),
    lastUsedAt: days(0),
    synced: true,
    biometric: true,
  },
  {
    id: "pk_3",
    service: "Cloudflare",
    domain: "cloudflare.com",
    device: "MacBook Pro 16″",
    platform: "macOS",
    createdAt: days(120),
    lastUsedAt: days(6),
    synced: false,
    biometric: true,
  },
  {
    id: "pk_4",
    service: "Notion",
    domain: "notion.so",
    device: "iPad Pro",
    platform: "iPadOS",
    createdAt: days(18),
    lastUsedAt: days(3),
    synced: true,
    biometric: false,
  },
];

export const seedOtp: OtpAccount[] = [
  {
    id: "otp_1",
    issuer: "GitHub",
    account: "pavank@novasafe.io",
    secret: "JBSWY3DPEHPK3PXP",
    favorite: true,
    addedAt: days(180),
  },
  {
    id: "otp_2",
    issuer: "Google",
    account: "pavank@novasafe.io",
    secret: "KRSXG5BAONSWG4TFOQ",
    favorite: false,
    addedAt: days(220),
  },
  {
    id: "otp_3",
    issuer: "AWS",
    account: "novasafe-admin",
    secret: "MFRGGZDFMZTWQ2LK",
    favorite: false,
    addedAt: days(60),
  },
  {
    id: "otp_4",
    issuer: "Cloudflare",
    account: "pavank@novasafe.io",
    secret: "NB2HI4DTHIXS653X",
    favorite: true,
    addedAt: days(95),
  },
  {
    id: "otp_5",
    issuer: "Stripe",
    account: "founder@novasafe.io",
    secret: "OBQXG43XN5ZGI",
    favorite: false,
    addedAt: days(40),
  },
];

export const seedDocs: VaultDocument[] = [
  {
    id: "doc_1",
    name: "Passport.pdf",
    folder: "Identity",
    size: 482_113,
    kind: "pdf",
    uploadedAt: days(120),
    shared: ["partner@novasafe.io"],
    tags: ["id"],
    versions: 2,
  },
  {
    id: "doc_2",
    name: "Aadhaar.pdf",
    folder: "Identity",
    size: 318_220,
    kind: "pdf",
    uploadedAt: days(120),
    shared: [],
    tags: ["id"],
    versions: 1,
  },
  {
    id: "doc_3",
    name: "PAN-Card.jpg",
    folder: "Identity",
    size: 211_004,
    kind: "image",
    uploadedAt: days(220),
    shared: [],
    tags: ["id"],
    versions: 1,
  },
  {
    id: "doc_4",
    name: "Lease-Agreement-2026.pdf",
    folder: "Contracts",
    size: 1_204_812,
    kind: "pdf",
    uploadedAt: days(30),
    shared: ["legal@novasafe.io"],
    tags: ["legal"],
    versions: 3,
  },
  {
    id: "doc_5",
    name: "ITR-AY2025-26.pdf",
    folder: "Tax",
    size: 902_311,
    kind: "pdf",
    uploadedAt: days(70),
    shared: [],
    tags: ["tax"],
    versions: 1,
  },
  {
    id: "doc_6",
    name: "Recovery-Kit.pdf",
    folder: "Recovery",
    size: 122_080,
    kind: "pdf",
    uploadedAt: days(14),
    shared: [],
    tags: ["recovery"],
    versions: 1,
  },
];

export const seedInvites: ShareInvite[] = [
  {
    id: "sh_1",
    itemTitle: "Netflix",
    sharedWith: "partner@novasafe.io",
    role: "viewer",
    state: "accepted",
    createdAt: days(15),
  },
  {
    id: "sh_2",
    itemTitle: "Lease-Agreement-2026.pdf",
    sharedWith: "legal@novasafe.io",
    role: "editor",
    state: "accepted",
    createdAt: days(8),
  },
  {
    id: "sh_3",
    itemTitle: "Hetzner — eu-fsn-01",
    sharedWith: "ops@novasafe.io",
    role: "viewer",
    state: "pending",
    createdAt: days(2),
  },
];

export const seedDevices: Device[] = [
  {
    id: "dv_1",
    name: "MacBook Pro 16″",
    platform: "macOS 16.3",
    location: "Pune, IN",
    lastActive: days(0),
    trusted: true,
    current: true,
  },
  {
    id: "dv_2",
    name: "iPhone 17 Pro",
    platform: "iOS 19.1",
    location: "Pune, IN",
    lastActive: days(0),
    trusted: true,
    current: false,
  },
  {
    id: "dv_3",
    name: "iPad Pro",
    platform: "iPadOS 19.0",
    location: "Mumbai, IN",
    lastActive: days(3),
    trusted: true,
    current: false,
  },
  {
    id: "dv_4",
    name: "Chrome — Windows",
    platform: "Windows 11",
    location: "Bengaluru, IN",
    lastActive: days(12),
    trusted: false,
    current: false,
  },
];

export const seedSessions: Session[] = [
  {
    id: "ss_1",
    device: "MacBook Pro 16″",
    ip: "103.21.58.12",
    location: "Pune, IN",
    startedAt: days(0),
  },
  {
    id: "ss_2",
    device: "iPhone 17 Pro",
    ip: "103.21.58.12",
    location: "Pune, IN",
    startedAt: days(0),
  },
  {
    id: "ss_3",
    device: "Chrome — Windows",
    ip: "49.207.11.4",
    location: "Bengaluru, IN",
    startedAt: days(12),
  },
];

export const seedActivity: ActivityEvent[] = [
  { id: "ev_1", kind: "login", message: "Signed in from MacBook Pro 16″", at: days(0) },
  { id: "ev_2", kind: "item", message: "Updated password for GitHub", at: days(4) },
  {
    id: "ev_3",
    kind: "share",
    message: "Shared Lease-Agreement with legal@novasafe.io",
    at: days(8),
  },
  { id: "ev_4", kind: "security", message: "New device authorised: iPhone 17 Pro", at: days(45) },
  { id: "ev_5", kind: "item", message: "Created passkey for Notion", at: days(18) },
];

export const seedInvoices: Invoice[] = [
  {
    id: "inv_2026_05",
    number: "NS-2026-05",
    amount: 9.0,
    currency: "USD",
    paidAt: days(4),
    status: "paid",
  },
  {
    id: "inv_2026_04",
    number: "NS-2026-04",
    amount: 9.0,
    currency: "USD",
    paidAt: days(34),
    status: "paid",
  },
  {
    id: "inv_2026_03",
    number: "NS-2026-03",
    amount: 9.0,
    currency: "USD",
    paidAt: days(64),
    status: "paid",
  },
];
